global:
  scrape_interval:     1m
  evaluation_interval: 1m

scrape_configs:
  # Job that polls the nomad prometheus metric endpoints
  - job_name: nomad-metrics
    consul_sd_configs:
      - server: https://consul.${domain}
        services: ['nomad-client', 'nomad']
    relabel_configs:
      - source_labels: ['__meta_consul_tags']
        regex: '(.*)http(.*)'
        action: keep
    metrics_path: /v1/metrics
    params:
      format: ['prometheus']

  # Job that polls the traefik instance's metric endpoints
  - job_name: traefik-metrics
    consul_sd_configs:
      - server: https://consul.${domain}
        services: ['traefik-metrics']
    metrics_path: /metrics


  # Job that polls the node-exporter instance's metric endpoint
  - job_name: node-metrics
    consul_sd_configs:
      - server: https://consul.${domain}
        services: ['node-exporter']
    metrics_path: /metrics

  # Job that polls the exporter-postgres instance's metric endpoint
  - job_name: postgres-metrics
    consul_sd_configs:
      - server: https://consul.${domain}
        services: ['prometheus-exporter-postgres']
    metrics_path: /metrics

  # Job that polls the home-assistant instance's metric endpoint
  - job_name: home-assistant-metrics
    consul_sd_configs:
      - server: https://consul.${domain}
        services: ['hass']
    metrics_path: /api/prometheus
    authorization:
      credentials_file: /etc/home-assistant/credentials